import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111827',
  },
  headerSubtitle: {
    fontSize: 10,
    color: '#6b7280',
  },
  slideContainer: {
    marginBottom: 20,
    breakInside: 'avoid',
  },
  slideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: '#f3f4f6',
    padding: 5,
    borderRadius: 4,
  },
  slideNumber: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#4b5563',
    marginRight: 10,
  },
  slideImage: {
    width: '100%',
    height: 200,
    objectFit: 'contain',
    marginBottom: 10,
    borderRadius: 4,
    border: '1pt solid #e5e7eb',
  },
  content: {
    fontSize: 10,
    lineHeight: 1.5,
    color: '#374151',
    textAlign: 'justify',
  },
  // Horizontal Layout Specifics
  horizontalLayoutContainer: {
    flexDirection: 'row',
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    paddingBottom: 20,
  },
  leftColumn: {
    width: '40%',
    paddingRight: 15,
  },
  rightColumn: {
    width: '60%',
  },
  horizontalImage: {
    width: '100%',
    height: 150,
    objectFit: 'contain',
    borderRadius: 4,
    border: '1pt solid #e5e7eb',
  },
});

interface SlideData {
  slide_number: number;
  content: string;
  expandedContent?: string;
  image?: string;
}

interface PDFExportProps {
  slides: SlideData[];
  layout: 'vertical' | 'horizontal';
  title?: string;
}

// Helper to strip markdown (basic)
const cleanText = (text: string) => {
  if (!text) return "";
  return text
    .replace(/#{1,6}\s/g, '') // Remove headers
    .replace(/\*\*/g, '')     // Remove bold
    .replace(/\*/g, '')       // Remove italic
    .replace(/`/g, '')        // Remove code ticks
    .replace(/\[(.*?)\]\(.*?\)/g, '$1'); // Remove links, keep text
};

export const PDFDocument = ({ slides, layout, title = "Lecture Notes" }: PDFExportProps) => (
  <Document>
    <Page size="A4" style={styles.page} orientation={layout === 'horizontal' ? 'landscape' : 'portrait'}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>{title}</Text>
        <Text style={styles.headerSubtitle}>Generated by UnSlide</Text>
      </View>

      {slides.length === 0 ? (
        <Text style={{ fontSize: 12, color: '#6b7280', textAlign: 'center', marginTop: 50 }}>
          No slides available to export.
        </Text>
      ) : (
        slides.map((slide, index) => (
        <View key={index} wrap={false}>
          {layout === 'vertical' ? (
            <View style={styles.slideContainer}>
              <View style={styles.slideHeader}>
                <Text style={styles.slideNumber}>Slide {slide.slide_number}</Text>
              </View>
              {slide.image && (
                <Image 
                  src={slide.image} 
                  style={styles.slideImage} 
                />
              )}
              <Text style={styles.content}>
                {cleanText(slide.expandedContent || slide.content)}
              </Text>
            </View>
          ) : (
            <View style={styles.horizontalLayoutContainer}>
              <View style={styles.leftColumn}>
                <View style={styles.slideHeader}>
                  <Text style={styles.slideNumber}>Slide {slide.slide_number}</Text>
                </View>
                {slide.image && (
                  <Image 
                    src={slide.image} 
                    style={styles.horizontalImage} 
                  />
                )}
              </View>
              <View style={styles.rightColumn}>
                <Text style={styles.content}>
                  {cleanText(slide.expandedContent || slide.content)}
                </Text>
              </View>
            </View>
          )}
        </View>
      ))
      )}
      
      <Text style={{ position: 'absolute', bottom: 30, left: 0, right: 0, textAlign: 'center', fontSize: 8, color: '#9ca3af' }} render={({ pageNumber, totalPages }) => (
        `${pageNumber} / ${totalPages}`
      )} fixed />
    </Page>
  </Document>
);
